# Generated by Django 6.1 on 2026-08-18 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(blank=True, default='', max_length=50)),
                ('truck_number', models.CharField(blank=True, default='', max_length=50)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=100)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('truck_mpg', models.FloatField(default=6.5)),
                ('fuel_price_preset', models.FloatField(default=4.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_used', models.FloatField()),
                ('total_distance', models.FloatField()),
                ('total_driving_hours', models.FloatField()),
                ('fuel_required', models.FloatField(default=0.0)),
                ('fuel_cost', models.FloatField(default=0.0)),
                ('total_trip_cost', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='planner.driverprofile')),
            ],
        ),
    ]
